spring:
    mvc:
        view:
            prefix: /WEB-INF/view/
            suffix: .jsp

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: MYSQL
        hibernate:
            ddl-auto: validate
        show-sql: true


    #jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    #database: H2
    #generate-ddl: false
    #open-in-view: false
    #show-sql: true
        #hibernate:
        #ddl-auto: validate
        #naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        #properties:
        #hibernate.cache.use_second_level_cache: true
        #hibernate.cache.use_query_cache: false
        #hibernate.generate_statistics: true
        #hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory


    datasource:
        url: jdbc:mysql://localhost/city?characterEncoding=utf8&amp;useSSL=false&amp;autoReconnection=true
        username: root
        password: qwer1234
        driverClassName: com.mysql.jdbc.Driver